# Managed by Ansible: configure_grafana_log_forwarding.yml
destination d_grafana_loki {
    syslog("{{ synology_loki_syslog_host }}"
        transport("tcp")
        port({{ synology_loki_syslog_port }})
        disk-buffer(
            reliable(yes)
            disk-buf-size(67108864)
            mem-buf-size(1048576)
        )
    );
};

log {
    source(src);
    destination(d_grafana_loki);
    flags(flow-control);
};
