[dbservers]
postgresql[01:01].myrobertson.net

[proxmox_cert_nodes:children]
proxmox_cert_nodes_cl0
proxmox_cert_nodes_cl1

[proxmox_cert_nodes_cl0]
# Add cl0 Proxmox node FQDNs/IPs for bootstrap rollout.

[proxmox_cert_nodes_cl0:vars]
proxmox_cert_cluster_san=cl0.myrobertson.net

[proxmox_cert_nodes_cl1]
# Add cl1 Proxmox node FQDNs/IPs for bootstrap rollout.

[proxmox_cert_nodes_cl1:vars]
proxmox_cert_cluster_san=cl1.myrobertson.net
