[dbservers]
postgresql[01:01].stage.myrobertson.net

[powerdns]
192.168.7.201

[powerdns-recurse]
192.168.7.202

[proxmox_cert_nodes:children]
proxmox_cert_nodes_cl0
proxmox_cert_nodes_cl1

[proxmox_cert_nodes_cl0]
# cl0 cluster nodes
192.168.11.3 ansible_user=root ansible_python_interpreter=/usr/bin/python3
192.168.11.4 ansible_user=root ansible_python_interpreter=/usr/bin/python3
192.168.11.5 ansible_user=root ansible_python_interpreter=/usr/bin/python3

[proxmox_cert_nodes_cl0:vars]
proxmox_cert_cluster_san=cl0.myrobertson.net

[proxmox_cert_nodes_cl1]
# cl1 cluster nodes
192.168.88.100 ansible_user=root ansible_python_interpreter=/usr/bin/python3
192.168.88.101 ansible_user=root ansible_python_interpreter=/usr/bin/python3
192.168.88.102 ansible_user=root ansible_python_interpreter=/usr/bin/python3

[proxmox_cert_nodes_cl1:vars]
proxmox_cert_cluster_san=cl1.myrobertson.net

[vault]
vault.myrobertson.net