---
- name: Install Free Range Routing (FRR) 
  ansible.builtin.apt:
    name: frr
    state: present
    update_cache: yes

- name: Enable Free Range Routing (FRR) 
  ansible.builtin.systemd_service:
    state: started
    name: frr

- name: Enable fabricd in fabric daemon file
  ansible.builtin.lineinfile:
    path: /etc/frr/daemons
    search_string: '^fabricd='
    line: fabricd=yes
  notify: restart frr service

- name: Script to restart frr when interfaces are brought up
  ansible.builtin.template:
    src: if-up.d_en0x.j2
    dest: /etc/network/if-up.d/en0x
    owner: root
    group: root
    mode: '0755' 

- name: Script to restart frr when loopback resets
  ansible.builtin.template:
    src: if-up.d_lo.j2
    dest: /etc/network/if-up.d/lo
    owner: root
    group: root
    mode: '0755' 

- name: Configure OpenFabric
  ansible.builtin.template:
    src: frr.conf.local.j2
    dest: /etc/frr/frr.conf.local
    owner: root
    group: root
    mode: '0755'
  notify: restart frr service
