---
- import_playbook: powerdns_servers.yml
- import_playbook: vault_server.yml
- import_playbook: ../../ansible/proxmox/provision_certificates.yml
  tags:
    - certs
    - proxmox_certs
- import_playbook: ../../ansible/proxmox/ceph_admin_portal.yml
  tags:
    - ceph_dashboard
    - ceph_admin_portal
